const listaProiecte = [
    {
        "id"        : "1",
        "nume"      : "Notes App",
        "descriere" : "Aplicație de notițe. Extrem de customizabilă în ceea ce privește culorile interfeței. Funcționalități ce asigură o experiență plăcută.",
        "functionalitati" : [
            "Funcționalități de Creare, Editare, Ștergere, Arhivare a notițelor",
            "Customizare a culorilor interfeței",
            "Customizare a culorilor notițelor",
            "Adăugare poze în notițe",
            "Posibilitate de a adăuga o notiță la 'favorite'",
            "Funționalitate de filtrare a notițelor în funcție de dată, text, etc, descrescător sau crescător",
            "Backup și restore a bazei de date",
        ],
        "poza_proiect" : "poze_proiecte/notesapp1.png",
        "poze" : [
            "poze_proiecte/notesapp2.jpg",
            "poze_proiecte/notesapp3.jpg",
            "poze_proiecte/notesapp4.jpg",
            "poze_proiecte/notesapp5.jpg",
            "poze_proiecte/notesapp6.jpg",
            "poze_proiecte/notesapp7.jpg",
        ],           
    },
    {
        "id"        : "2",
        "nume"      : "Calculator",
        "descriere" : "Aplicație pentru un calculator simplu.",
        "functionalitati" : [ "Toate operațiile uzuale" ],
        "poza_proiect" : "poze_proiecte/calculator1.jpg",
        "poze" : [
            "poze_proiecte/calculator2.jpg",
            "poze_proiecte/calculator3.jpg",
            "poze_proiecte/calculator4.jpg",
            "poze_proiecte/calculator5.jpg",
            "poze_proiecte/calculator6.jpg",
            "poze_proiecte/calculator7.jpg",
        ]
    },
    {
        "id"        : "3",
        "nume"      : "Vremea Romania",
        "descriere" : "Aplicație meteo, vizualizează detalii despre temperatură, umiditate, viteza vântului pt reședințele de județ a României.",
        "functionalitati" : [
            "Apelarea API-ului Open Weather pentru culegerea de date",
            "Alegerea simplă a județului prin atingere pe imaginea CSV",
            "În funcție de județul ales se afișează datele de vreme pentru ziua respectivă, date de către API-ul Open Weather",
        ],
        "poza_proiect" : "poze_proiecte/vremea1.png",
        "poze" : [
            "poze_proiecte/vremea2.jpg",
            "poze_proiecte/vremea3.jpg",
            "poze_proiecte/vremea4.jpg",
            "poze_proiecte/vremea5.jpg",
            "poze_proiecte/vremea6.jpg",
            "poze_proiecte/vremea7.jpg",
        ],
    },
    {
        "id"        : "4",
        "nume"      : "IP Calculator",
        "descriere" : "Folosind Calculatorul IP, puteți calcula adresa de broadcast și rețea, numărul de gazde și intervalul de gazde pe baza unei adrese IP și a unei măști de subrețea date ca input.",
        "functionalitati" : [
            "Ca input se da o adresă IP și un Subnet Mask - care poate fi ales sub formă de adresă sau de biți, din liste drop down",
            "Output-ul constă in afișarea numărului de host-uri, clasa adresei IP, range-ul host-urilor",
            "Se pot vedea și notațiile hexadecimale sau binare pentru input-ul decimal",
        ],
        "poza_proiect" : "poze_proiecte/ip1.png",
        "poze" : [
            "poze_proiecte/ip2.jpg",
            "poze_proiecte/ip3.jpg",
            "poze_proiecte/ip4.jpg",
            "poze_proiecte/ip5.jpg",
            "poze_proiecte/ip6.jpg",
            "poze_proiecte/ip7.jpg",
        ],
    },
    {
        "id"        : "5",
        "nume"      : "Video Downloader",
        "descriere" : "Aplicație pentru descărcarea videoclipurilor. Descărcați videoclipuri folosind aplicația Video Downloader. Descărcați întregul videoclip sau doar secțiuni ale videoclipului folosind modulul de tăiere video. Descărcați videoclipuri de pe TikTok, Instagram, Facebook etc.",
        "functionalitati" : [
            "Aplicația accesează API-ul meu, care constă dintr-o aplicație Python - Flask.",
            "Ca input se trimite către API un link de tiktok/yewtube/piped/vimeo/dailymotion/etc - sau doar ID-ul unui clip de YouTube, fără partea de 'https://youtu.be/' (pentru a fi acceptată de către Google Playstore)",
            "Opțional se pot trimite ca input și timpul de start și timpul de sfârșit - iar API-ul returnează doar acel segment de videoclip",
            "Videoclipurile se stochează local, în folderul aplicației. Se pot accesa din galeria aplicației",
            "Din galeria aplicației clipurile pot fi vizualizate, li se pot schimba numele, se pot șterge, sau se pot distribui pe rețelele sociale, google drive, etc",
        ], 
        "poza_proiect" : "poze_proiecte/videodownloader1.png",
        "poze" : [
            "poze_proiecte/videodownloader2.jpg",
            "poze_proiecte/videodownloader3.jpg",
            "poze_proiecte/videodownloader4.jpg",
            "poze_proiecte/videodownloader5.jpg",
            "poze_proiecte/videodownloader6.jpg",
            "poze_proiecte/videodownloader7.jpg",    
        ],
    },
    {
        "id"        : "6",
        "nume"      : "RoSpringVet 1",
        "descriere" : "Aplicație pentru gestionarea unui cabinet veterinar. Prima versiune este o aplicație strict browser, de tip MPA, realizată cu Java - Spring Boot și template engine-ul Thymeleaf. Aplicația poate înlocui registrul fizic de programări/vizite, fiind mult mai rapidă în găsirea animalelor, cu toate vizitele, programările, tratamentele în desfășurare",
        "functionalitati" : [
            "Funcționalități de înregistrare, autentificare și autorizare pentru diferiți utilizatori - realizate cu Spring Security",
            "Sistem de înștiințare prin e-mail",
            "Funcții CRUD pentru animale, programări, vizite, tratamente, etc",
            "Funcționaltăți de filtrare în funcție de dată, nume, stare, etc",
        ],
        "poza_proiect"  : "poze_proiecte/rospringvet1.png",
        "poze" : [],
        "linkVideo" : "",
    },
    {
        "id"        : "7",
        "nume"      : "Astronomy App",
        "descriere" : "Aplicație de vizualizare a APOD-urilor (Astronomy Picture Of the Day) date de către NASA. Aplicația se folosește de API-ul NASA pentru a prelua imaginea/clipul, descrierea, etc pentru o anumită zi aleasă de utilizator.",
        "functionalitati" : [
            "În funcție de data aleasă, se va afișa APOD-ul pentru ziua respectivă. Cheia API-ului permite 2000 de apelări pe oră.",
            "Funcționalitate de salvare a APOD-urilor la favorite - vor apărea în galeria aplicației",
            "Import/Export a APOD-urilor salvate",    
        ],
        "poza_proiect" : "poze_proiecte/apod1.jpg",
        "poze" : [
            "poze_proiecte/apod2.jpeg",
            "poze_proiecte/apod3.jpeg",
            "poze_proiecte/apod4.jpeg",
            "poze_proiecte/apod5.jpeg",
            "poze_proiecte/apod6.jpeg",
            "poze_proiecte/apod7.jpeg",    
        ],
    },
]
export {listaProiecte}